# Numpy array Attributes

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
# dimensions

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)


print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")



x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


# Multi dimensional array slicing

In [4]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [6]:
x2[:2,:3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]], dtype=int32)

In [8]:
x2[:3, ::2]  # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]], dtype=int32)

In [9]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]], dtype=int32)

# creating copy of a subarray 

In [11]:
x2_sub_copy = x2[:2, :2].copy()

#! without copy, x2_sub_copy will share the same data

# Reshaping arrays (input is shape tuple)

In [13]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1d array shape

![](https://live.staticflickr.com/65535/54976246130_eb80481a96_b.jpg)

np.newaxis --> adds a new dimension

![](https://live.staticflickr.com/65535/54976201283_d4c09d08b0_c.jpg)

# Array concatenation and splitting

while concating 2d arrays remember we are first concatinating 

row wise (vertical stack) this is the first axis --> 0






In [ ]:
# concatenate along the second axis (zero-indexed)
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])



array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [17]:

np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

![](https://live.staticflickr.com/65535/54976350525_79ed546c5d_c.jpg)

# Splitting of array

we pass a list of split points

In [18]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [19]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

![](https://live.staticflickr.com/65535/54976404180_f8ac89af84_c.jpg)