# Data types in Python

![](https://live.staticflickr.com/65535/54972313373_e637e42d63_c.jpg)

Notice the difference here: a C integer is essentially a label for a position in memory whose bytes encode an integer value. A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value. This extra information in the Python integer structure is what allows Python to be coded so freely and dynamically. All this additional information in Python types comes at a cost, however, which becomes especially apparent in structures that combine many of these objects.

L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

But this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object. In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array. The difference between a dynamic-type list and a fixed-type (NumPy-style) array is illustrated in the following figure:

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/array_vs_list.png)

python also has a array module but it is efficient only in storage not in operations.

1. Numpy arrays have fixed data types
2. If there are different types in the np array it tries to upcast


In [1]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4], dtype='float32')
# array with explicit typing

array([1., 2., 3., 4.], dtype=float32)

In [4]:
# special numpy methods 

np.zeros(10) --> intialises array with number zero of array

np.ones((3,5)) --> initialises 3*5 shape array with ones

np.full((3,5), 3.14) --> initialises 3*5 shape array with 3.14

# Numpy arrange and linspace

1. np.arrange(0,20,2) --> start, stop, step_size
2. np.linspace(0,1,5) --> start, stop, number of values 

In [8]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
# ✅ np.random.normal gives you random x-values (data points) that are sampled from a normal distribution.
np.random.normal(0, 1, (3, 3))

array([[ 0.90919997, -0.67052417, -0.64761068],
       [-0.69815359,  1.43974891,  0.02617086],
       [ 0.41473242, -0.7710367 ,  1.33289194]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])