Doing vectorised operations are faster thru numpy like addition, multiplication of two arrays instead of traditional python loops it is better to use numpy ufuncs

just do operations on vectors normally 

like 1/arr

2**arr

and without loops it will be executed

![](https://live.staticflickr.com/65535/54976472424_bbd48fc8c5_c.jpg)

![](https://live.staticflickr.com/65535/54976473214_e8f1863f53_z.jpg)

instead of abs(x)

use np.abs(x) ---> faster

In [1]:
import numpy as np
theta = np.linspace(0, np.pi, 3)

In [2]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]



Specifying output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:


In [3]:


x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)



[ 0. 10. 20. 30. 40.]


In [4]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


out argument used for saving space

# Aggregates

just add reduce add the end

![](https://live.staticflickr.com/65535/54976411473_efcd064c36_c.jpg)

if we want to store intermediate results of computation

![](https://live.staticflickr.com/65535/54976534535_38cbb7a7ff_c.jpg)

![](https://live.staticflickr.com/65535/54976244186_0e4d5b75fa_c.jpg)

outer is cross product type shit but for every operator

it also exists for add and other operators


In [7]:
x = np.arange(1,6)

np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])